# -*- coding: utf-8 -*-
"""tarefa_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aSkCZuzhzfnZrst06NhHBaVb855ZiFUg
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#Importando planilha e tradução de colunas em Português.
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data')

colunas_ptbr = [
    'classe',
    'alcool',
    'acido_malico',
    'cinzas',
    'alcalinidade_de_cinzas',
    'magnesio',
    'fenois_totais',
    'flavanoides',
    'fenois_nao_flavanoides',
    'proantocianinas',
    'intensidade_de_cor',
    'matiz',
    'od280_od315_de_vinhos_diluidos',
    'prolina'
]

df.columns = colunas_ptbr

#Definição da coluna 'classe' como um objeto
df['classe'] = df['classe'].astype(str)
df.dtypes

#Exploração inicial dos dados

#Visão geral do dataframe:
df.info()

#Descrição geral do dataframe:
df.describe()

#Cotagem das diferentes classes conditas:

contagem_classes = df['classe'].value_counts()
print("Contagem das diferentes classes:")
print(contagem_classes)

#Estatísticas descritivas para as colunas solicitadas.

statistics = df[['alcool', 'acido_malico', 'magnesio', 'matiz']].describe()
print("\nEstatísticas descritivas:")
print(statistics)

#Insights:

print("\nInsights:")
for ins in ['alcool', 'acido_malico', 'magnesio', 'matiz']:
    media = df[ins].mean()
    mediana = df[ins].median()
    std_dev = df[ins].std()
    min_val = df[ins].min()
    max_val = df[ins].max()

    print(f"- {ins}:")
    print(f"  Média: {media:.2f}, Mediana: {mediana:.2f}, Desvio Padrão: {std_dev:.2f}")
    print(f"  Mínimo: {min_val:.2f}, Máximo: {max_val:.2f}")

# Criação dos boxplots

#Magnésio
plt.subplot(2, 1, 2)
sns.boxplot(x=df['magnesio'])
plt.title('Boxplot de Magnésio')

#Prolina

plt.subplot(2, 1, 1)
sns.boxplot(x=df['prolina'])
plt.title('Boxplot de Prolina')

#Cinzas

plt.subplot(2, 1, 2)
sns.boxplot(x=df['cinzas'])
plt.title('Boxplot de Cinzas')

#Álcool

plt.subplot(2, 1, 2)
sns.boxplot(x=df['alcool'])
plt.title('Boxplot de Álcool')

#Criando os Boxplots por classe:

colunas = ['magnesio', 'fenois_totais', 'acido_malico', 'alcool']

for box in colunas:
  plt.figure(figsize=(10, 6))
  df.boxplot(column=box, by='classe')
  plt.title(f'Boxplot de {box} por Classe')
  plt.suptitle('')
  plt.ylabel(box)
  plt.show()

#Histograma da coluna 'fenois_totais'

plt.figure(figsize=(10, 6))
sns.histplot(df['fenois_totais'], bins=10, kde=True)
plt.title('Histograma de Fenóis Totais')
plt.xlabel('Fenóis Totais')
plt.ylabel('Frequência')
plt.grid(True)
plt.show()

#Histograma da coluna 'fenois_totais' apenas para classe 3:

vinhos_3 = df[df['classe'] == '3']

plt.figure(figsize=(10, 6))
sns.histplot(vinhos_3['fenois_totais'], bins=10, kde=True)
plt.title('Histograma de Fenóis Totais (Classe 3)')
plt.xlabel('Fenóis Totais')
plt.ylabel('Frequência')
plt.grid(True)
plt.show()